### ISSUE TITLE
Dogecoin open source contributor

### ISSUE THREAD

**Issue by sabotagebeats** [BTCMedia/B22-Open-Source-Program#76]
https://github.com/dogecoin/dogecoin/pull/2236

**Comment by aioromo** [comment]
LG!!! Bitcoin is for everyone!

Tell your friends to use promo code **DOGE** for 10% off any Bitcoin 2022 passes on Tixr checkout, which also has a payment plan! 

🌋

https://bit.ly/3AIOQGV
